<template>
  <q-page padding>
      <q-page-sticky position="top-right">
      <q-select
        filter
        inset
        autofocus-filter
        filter-placeholder="search"
        placeholder="Input Script"
        v-model="script2"
        class="q-ma-sm col-md-3"
        :options="scriptsOutput"
      />
    </q-page-sticky>
      <h4> {{script1}} <q-spinner-comment color="dark" :size="30" v-show="loading"/> </h4>

      <div style="text-align: right">
      <span class="text-red-2"> X</span> : Approximate equivalent <br/>
      <span class="text-blue-4"> Y</span> : Equivalent with diacritic <br/>
      </div>
      <h5> Vowels</h5>
      <list-char :chars="charList[0]" :script1="script1" :script2="script2" :chars1="charListC['script1'][0]"
        :chars2="charListC['script2'][0]" :charsIr="charListC['script1hk'][0]"> </list-char>
      <b> Others </b> <br/><br/>
      <list-char :chars="charList[1]" :script1="script1" :script2="script2" :chars1="charListC['script1'][1]"
        :chars2="charListC['script2'][1]" :charsIr="charListC['script1hk'][1]"> </list-char>
      <b> Combining Signs </b> <br/><br/>
      <list-char :chars="charList[2]" :script1="script1" :script2="script2" :chars1="charListC['script1'][2]"
        :chars2="charListC['script2'][2]" :charsIr="charListC['script1hk'][2]"> </list-char>
      <h5> Consonants </h5>
      <list-char :chars="chars" :script1="script1" :script2="script2" v-for="(chars, index) in charList[3]" :key="index"
      :chars1="charListC['script1'][3][index]" :chars2="charListC['script2'][3][index]" :charsIr="charListC['script1hk'][3][index]"> </list-char>
      <b> South-Indic Consonants </b> <br/><br/>
      <list-char :chars="charList[4]" :script1="script1" :script2="script2" :chars1="charListC['script1'][4]"
        :chars2="charListC['script2'][4]" :charsIr="charListC['script1hk'][4]"> </list-char>
      <b> North-Indic Consonants with Nukta </b> <br/><br/>
      <list-char :chars="charList[5]" :script1="script1" :script2="script2" :chars1="charListC['script1'][5]"
        :chars2="charListC['script2'][5]" :charsIr="charListC['script1hk'][5]"> </list-char>
      <b> Sinhala Pre-nasalized Consonants </b> <br/><br/>
      <list-char :chars="charList[6]" :script1="script1" :script2="script2" :chars1="charListC['script1'][6]"
        :chars2="charListC['script2'][6]" :charsIr="charListC['script1hk'][6]"> </list-char>
      <h5> CV Syllables with KA </h5>
      <list-char :chars="charList[10]" :script1="script1" :script2="script2" :chars1="charListC['script1'][10]"
        :chars2="charListC['script2'][10]" :charsIr="charListC['script1hk'][10]"> </list-char>
      <list-char :chars="charList[11]" :script1="script1" :script2="script2" :chars1="charListC['script1'][11]"
        :chars2="charListC['script2'][11]" :charsIr="charListC['script1hk'][11]"> </list-char>
      <list-char :chars="charList[12]" :script1="script1" :script2="script2" :chars1="charListC['script1'][12]"
        :chars2="charListC['script2'][12]" :charsIr="charListC['script1hk'][12]"> </list-char>
      <h5> Conjuncts with KA</h5>
      <list-char :chars="charList[9]" :script1="script1" :script2="script2" :chars1="charListC['script1'][9]"
        :chars2="charListC['script2'][9]" :charsIr="charListC['script1hk'][9]"> </list-char>
      <h5> Numerals </h5>
      <list-char :chars="charList[7]" :script1="script1" :script2="script2" :chars1="charListC['script1'][7]"
        :chars2="charListC['script2'][7]" :charsIr="charListC['script1hk'][7]"> </list-char>
      <h5> Others </h5>
      <list-char :chars="charList[8]" :script1="script1" :script2="script2" :chars1="charListC['script1'][8]"
        :chars2="charListC['script2'][8]" :charsIr="charListC['script1hk'][8]"> </list-char>

        <div v-show="typeof textNative[script1] !== 'undefined'">
        <h5> {{script1}} Text </h5>
        <div v-html="textNative[script1]" :class="script1.toLowerCase()"></div><br/>
        <transliterate :text="textNative[script1]" :src="script1" :tgt="script2" :sourcePreserve="false" :postOptions="[]"
        :preOptions="script1 === 'Urdu'? ['UrduShortNotShown'] : []">
        </transliterate>
      </div>
      <h5> Sanskrit Text </h5>
      <transliterate :text="quoteSa" src="HK" :tgt="script2" :sourcePreserve="true" :postOptions="[]">
      </transliterate> <br/>
      <transliterate :text="quoteSa" src="HK" :tgt="script1" :sourcePreserve="false" :postOptions="[]">
      </transliterate>
      <h5> Pali Text </h5>
      <transliterate :text="quotePa" src="HK" :tgt="script2" :sourcePreserve="true" :postOptions="[]">
      </transliterate> <br/>
      <transliterate :text="quotePa" src="HK" :tgt="script1" :sourcePreserve="false" :postOptions="[]">
      </transliterate>
      <h5> Notes </h5>
      <div class="q-body-1">For general character mapping notes, please refer to <router-link to="/script-matrix">Script Matrix </router-link>.</div><br/>
      <div class="q-body-1" v-html="notes[script1]"> </div>
      <h5 v-if="links[script1]"> Related Links </h5>
      <ol v-if="links[script1]" class="q-body-1">
      <li v-for="link in links[script1]" :key="link"> <a :href="link"> {{link}} </a> </li>
      </ol>

  </q-page>
</template>

<style>
</style>

<script>
import Controls from '../components/Controls'
import Learncard from '../components/Learncard'
import ListChar from '../components/ListChar'
import Transliterate from '../components/Transliterate'
import {ScriptMixin} from '../mixins/ScriptMixin'
import {QPageSticky, QSelect, QSpinnerComment} from 'quasar'

var _ = require('underscore')

export default {
  name: 'PageIndex',
  mixins: [ScriptMixin],
  components: {
    Controls,
    QPageSticky,
    QSpinnerComment,
    Transliterate,
    Learncard,
    QSelect,
    ListChar
  },
  computed: {
    conj: function () {
      var conj = []
      conj = this.dash.flatten(this.charList[3]).map(x => 'k' + x)
      conj = conj.map(x => x.replace('kha', 'ak'))
      conj = conj.map(x => x.replace('kak', 'kkha'))

      conj.push('k')
      return conj
    }
  },
  data () {
    return {
      options: {script: 'Devanagari', sourcePreserve: false},
      dash: _,
      loading: true,
      text: '',
      script1: this.$route.params.script,
      script2: 'IAST',
      charList: [
        ['a', 'A', 'i', 'I', 'u', 'U', 'R', 'RR', 'lR', 'lRR', 'e', 'ai', 'o', 'au'],
        ['E', 'O', 'aE', 'AE', 'aO'],
        ['aM', 'aH', 'a~'],
        [['ka', 'kha', 'ga', 'gha', 'Ga'], ['ca', 'cha', 'ja', 'jha', 'Ja'], ['Ta', 'Tha', 'Da', 'Dha', 'Na'],
          ['ta', 'tha', 'da', 'dha', 'na'], ['pa', 'pha', 'ba', 'bha', 'ma'], ['ya', 'ra', 'la', 'va'], ['za', 'Sa', 'sa', 'ha']],
        ['La', 'Za', 'r2a', 'n2a'],
        ['qa', 'qha', 'g2a', 'z2a', 'r3a', 'r3ha', 'fa', 'Ya'],
        ['n*ga', 'n*ja', 'n*Da', 'n*da', 'm*ba'],
        ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
        ['\'', 'oM', 'K', '.', '..'],
        [ 'kka', 'kkha', 'kga', 'kgha', 'kGa', 'kca', 'kcha', 'kja', 'kjha', 'kJa', 'kTa', 'kTha', 'kDa', 'kDha', 'kNa', 'kta', 'ktha', 'kda', 'kdha', 'kna', 'kpa', 'kpha', 'kba', 'kbha', 'kma', 'kya', 'kra', 'kla', 'kva', 'kza', 'kSa', 'ksa', 'ak', 'k' ],
        ['ka', 'kA', 'ki', 'kI', 'ku', 'kU', 'kR', 'kRR', 'klR', 'klRR', 'ke', 'kai', 'ko', 'kau'],
        ['kE', 'kO', 'kaE', 'kAE', 'kaO'],
        ['kaM', 'kaH', 'ka~']
      ],
      charListC: {
        'script1': [
          ['a', 'A', 'i', 'I', 'u', 'U', 'R', 'RR', 'lR', 'lRR', 'e', 'ai', 'o', 'au'],
          ['E', 'O', 'aE', 'AE', 'aO'],
          ['aM', 'aH', 'a~'],
          [['ka', 'kha', 'ga', 'gha', 'Ga'], ['ca', 'cha', 'ja', 'jha', 'Ja'], ['Ta', 'Tha', 'Da', 'Dha', 'Na'],
            ['ta', 'tha', 'da', 'dha', 'na'], ['pa', 'pha', 'ba', 'bha', 'ma'], ['ya', 'ra', 'la', 'va'], ['za', 'Sa', 'sa', 'ha']],
          ['La', 'Za', 'r2a', 'n2a'],
          ['qa', 'qha', 'g2a', 'z2a', 'r3a', 'r3ha', 'fa', 'Ya'],
          ['n*ga', 'n*ja', 'n*Da', 'n*da', 'm*ba'],
          ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
          ['\'', 'oM', 'K', '.', '..'],
          [ 'kka', 'kkha', 'kga', 'kgha', 'kGa', 'kca', 'kcha', 'kja', 'kjha', 'kJa', 'kTa', 'kTha', 'kDa', 'kDha', 'kNa', 'kta', 'ktha', 'kda', 'kdha', 'kna', 'kpa', 'kpha', 'kba', 'kbha', 'kma', 'kya', 'kra', 'kla', 'kva', 'kza', 'kSa', 'ksa', 'ak', 'k' ],
          ['ka', 'kA', 'ki', 'kI', 'ku', 'kU', 'kR', 'kRR', 'klR', 'klRR', 'ke', 'kai', 'ko', 'kau'],
          ['kE', 'kO', 'kaE', 'kAE', 'kaO'],
          ['kaM', 'kaH', 'ka~']
        ],
        'script2': [
          ['a', 'A', 'i', 'I', 'u', 'U', 'R', 'RR', 'lR', 'lRR', 'e', 'ai', 'o', 'au'],
          ['E', 'O', 'aE', 'AE', 'aO'],
          ['aM', 'aH', 'a~'],
          [['ka', 'kha', 'ga', 'gha', 'Ga'], ['ca', 'cha', 'ja', 'jha', 'Ja'], ['Ta', 'Tha', 'Da', 'Dha', 'Na'],
            ['ta', 'tha', 'da', 'dha', 'na'], ['pa', 'pha', 'ba', 'bha', 'ma'], ['ya', 'ra', 'la', 'va'], ['za', 'Sa', 'sa', 'ha']],
          ['La', 'Za', 'r2a', 'n2a'],
          ['qa', 'qha', 'g2a', 'z2a', 'r3a', 'r3ha', 'fa', 'Ya'],
          ['n*ga', 'n*ja', 'n*Da', 'n*da', 'm*ba'],
          ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
          ['\'', 'oM', 'K', '.', '..'],
          [ 'kka', 'kkha', 'kga', 'kgha', 'kGa', 'kca', 'kcha', 'kja', 'kjha', 'kJa', 'kTa', 'kTha', 'kDa', 'kDha', 'kNa', 'kta', 'ktha', 'kda', 'kdha', 'kna', 'kpa', 'kpha', 'kba', 'kbha', 'kma', 'kya', 'kra', 'kla', 'kva', 'kza', 'kSa', 'ksa', 'ak', 'k' ],
          ['ka', 'kA', 'ki', 'kI', 'ku', 'kU', 'kR', 'kRR', 'klR', 'klRR', 'ke', 'kai', 'ko', 'kau'],
          ['kE', 'kO', 'kaE', 'kAE', 'kaO'],
          ['kaM', 'kaH', 'ka~']
        ],
        'script1hk': [
          ['a', 'A', 'i', 'I', 'u', 'U', 'R', 'RR', 'lR', 'lRR', 'e', 'ai', 'o', 'au'],
          ['E', 'O', 'aE', 'AE', 'aO'],
          ['aM', 'aH', 'a~'],
          [['ka', 'kha', 'ga', 'gha', 'Ga'], ['ca', 'cha', 'ja', 'jha', 'Ja'], ['Ta', 'Tha', 'Da', 'Dha', 'Na'],
            ['ta', 'tha', 'da', 'dha', 'na'], ['pa', 'pha', 'ba', 'bha', 'ma'], ['ya', 'ra', 'la', 'va'], ['za', 'Sa', 'sa', 'ha']],
          ['La', 'Za', 'r2a', 'n2a'],
          ['qa', 'qha', 'g2a', 'z2a', 'r3a', 'r3ha', 'fa', 'Ya'],
          ['n*ga', 'n*ja', 'n*Da', 'n*da', 'm*ba'],
          ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
          ['\'', 'oM', 'K', '.', '..'],
          [ 'kka', 'kkha', 'kga', 'kgha', 'kGa', 'kca', 'kcha', 'kja', 'kjha', 'kJa', 'kTa', 'kTha', 'kDa', 'kDha', 'kNa', 'kta', 'ktha', 'kda', 'kdha', 'kna', 'kpa', 'kpha', 'kba', 'kbha', 'kma', 'kya', 'kra', 'kla', 'kva', 'kza', 'kSa', 'ksa', 'ak', 'k' ],
          ['ka', 'kA', 'ki', 'kI', 'ku', 'kU', 'kR', 'kRR', 'klR', 'klRR', 'ke', 'kai', 'ko', 'kau'],
          ['kE', 'kO', 'kaE', 'kAE', 'kaO'],
          ['kaM', 'kaH', 'ka~']
        ]
      },
      quoteSa: 'anirodham anutpAdam anucchedam azAzvatam .\nanekArtham anAnArtham anAgamam anirgamam ..\nyaH pratItyasamutpAdaM prapaJcopazamaM zivam .\ndezayAmAsa saMbuddhastaM vande vadatAM varam ..\n',
      quotePa: 'ye dhammA hetuppabhavA tesaM hetuM tathAgato Aha .\ntesaJca yo nirodho evaM vAdI mahAsamaNo ..\n',
      links: {
        'Buginese': ['https://r12a.github.io/scripts/buginese/'],
        'Burmese': ['https://r12a.github.io/scripts/myanmar/'],
        'SoraSompeng': ['http://scriptsource.org/cms/scripts/page.php?item_id=script_detail&key=Sora', 'https://www.unicode.org/L2/L2009/09189r-n3647r-sora-sompeng.pdf'],
        'WarangCiti': ['https://unicode.org/L2/L2012/12118-n4259-warang-citi.pdf'],
        'Tirhuta': ['http://scriptsource.org/cms/scripts/page.php?item_id=script_detail&key=Tirh']
      },
      notes: {
        'Tamil': '<b> Superscripted Tamil </b> <br/> <br/> Tamil has a deficient script compared to other Indic scripts as it lacks distinct characters for many voiced and aspirated consonants. Publishers had to resort to the use of Superscript (and sometimes subscript) numerals to represent these letters in Tamil. <br/><br/><b> Nativization Conventions </b><br/><br/> The following nativization conventions are automatically applied to the Tamil output to increase readability. <br/> <ul> <li>Anusvara and Chandrabindu are replaced by the corresponding nasal consonant if followed by a plosive <li>Intervocalic /ந/ is replaced by /ன/',
        'Sinhala': '<b> Sanskrit/Pali Orthography in Sinhala </b> <br/><br/> When Sinhala is used to write Sanskrit/Pali text, sometimes the short e/o are used to represent the Sanskrit long e/o. For instance, <span class="sinhala">නමො භගවතෙ</span> instead of <span class="sinhala">නමෝ භගවතේ</span> <br/><br/><b> Conjuncts </b> <br/><br/> Modern Sinhala does not extensively use conjuncts except for KSSA and the post-base forms of YA and RA. However, older texts, particularly for Pali/Sanskrit, extensively used conjuncts. For instance, <span class="sinhala">සම‍්මාසම‍්බුද්‍ධස‍්ස</span> instead of <span class="sinhala">සම්මාසම්බුද්ධස්ස</span>. Notice the use of conjoining conjuncts such as <span class="sinhala">ද්‍ධ</span> and touching letters such as <span class="sinhala">ස‍්ස</span>.',
        'TamilGrantha': 'Modern Tamil only adopts /ja/, /śa/, /ṣa/, /ha/ and the compound /śrī/ from Grantha into its character reportoire. However, there were some attempts to use the full complimentary set of Grantha letters to fill the gaps in the Tamil script (as compared to the pan-Indic system). This was probably done instead of using superscript numerals to increase the readability of the text (and the possible wide-spread familiarity with Grantha script few decades ago). One such attempt is shown below as used in the text called <a href="http://www.archive.org/stream/bhojacharitrama00sastgoog">Bhojacharitram</a>, published in 1916. <br/><img src="../statics/Grantha_Pulli.jpg"><br/> <span class="tamilgrantha">ப்ரார்ধ்யந்தஸ்ய நாஶஞ் ச <br/>முஞ்ஜঃ ஸம்க்ஷீயதாமிதி ॥ <br/>விঘ்​‌‍‌ேநஶஞ் ஸ ம​‌‍‌ேஹஶஞ் ச । <br/>ஹரிம் நগரவாஸிநঃ <br/>நদீபர்வத மா​‌‍‌ேஸদுঃ <br/>விப்ரா ​‌‍‌ேদஶாந்தரம் யயுঃ ॥</span> <br/> <br/>prārdhyantasya nāśañ ca <br/>muñjaḥ samkṣīyatāmiti .. <br/>vighneśañ sa maheśañ ca . <br/>harim nagaravāsinaḥ <br/>nadīparvata māseduḥ <br/>viprā deśāntaram yayuḥ .. <br/> <br/>  For technical reasons, the above only works with the e-Grantamil font. <br/><br/> A <a href="https://groups.google.com/d/msg/mintamil/tDwV_UwYJKc/AVCkX2KQFV4J">commentary</a> on the Jaina Epic Nilakesi published in 1936 also uses this technique intermittently to disambiguate Sanskrit words that will otherwise be ambigous in the Tamil script, along with the proper Grantha script for Sanskrit quotations. There also been other recent publications that employed this method to print Sanskrit.',
        'Thaana': 'Aksharamukha automatically uses އް to denote gemination. When އް appears as a glottal stop (at the end of words), it is denoted using ʔ. The Arabic-specific characters in Thaana are approximated to their closest Indic counterparts.',
        'MeeteiMayek': '<b> Historic Orthography </b> <br/><br/> Historically, Meetei Mayek had characters for the following: ī ū aḥ cha ña ṭa ṭha ḍa ḍha na śa ṣa :: <span class="meeteimayek">ꯑꫫ ꯑꫬ ꯑꫵ ꫢ ꫣ ꫤ ꫥ ꫦ ꫧ ꯅ ꫩ ꫪ</span>. But, they are not in vogue any more. By default, Aksharamukha does not use these characters. They are replaced by their closest approximations: i u ah ca na ta tha da dha na sa sa :: <span class="meeteimayek">ꯏ ꯎ ꯑꯍ꯭ ꯆ ꯅ ꯇ ꯊ ꯗ ꯙ ꯅ ꯁ ꯁ</span>. The historic characters are used only if the <i>preserve script</i> option is enabled.',
        'Malayalam': 'To preserve Chillus in the converted text, enable \'Presere source\'. Chillus will then be shown followed by a _.',
        'PhagsPa': 'Phagps does not use conjuncts except for subjoined -r,-v- and -y. Instead, it splits the words in syllabic chunks of the forms - [C]V, [C]VC and CCV. Thus <i>samudgate</i> becomes <i>sa mud ga te</i> <span class="phagspa">ꡛ ꡏꡟꡊ ꡂ ꡈꡠ</span>and <i>kleśa</i> becomes <i>kle śa</i> <span class="phagspa">ꡀꡙꡠ ꡚ</span>. However, this leads to an ambiguity. A word like <span class="phagspa">ꡛꡈ ꡋ</span> can be read as <i>stana</i> or <i>satna</i> in the absense of the any vowel signs. <br/><br/> Aksharamukha converts the input text into syllabic chunks automatically and also reverses thep process for the transliteration from PhagsPa to other scripts. ᠂ U+1802 is used as the word separator in PhagsPa text.',
        'IPA': 'The IPA conversion is based on the normalized prescriptive pronunication expected from a Sanskrit text. This may not accurately reflect variations that usually occur based on the target script or even based on the region it is being read. It will for most part fail for both Malayalam and Tamil as they have a phonemic orthography. For Tamil to IPA conversion, consider using <a href="http://anunaadam.appspot.com">Anunaadam</a> which is far more accurate.',
        'Telugu': ' <b> New Telugu characters </b> <br/><br/>ఴ is a historic Telugu letter that is equivalent to Tamil ழ. And Telugu also has it own Candrabindu characters అఀ. Being new characters, your Telugu font may not adequately support these characters. Please use an updated font to view these characters. <br/><br/> <b> Nativization Conventions </b> <br/><br/>The following nativization conventions are automatically applied to the Telugu output to increase readability. <br/> <ul> <li> Pure nasal consonants are replaced by Anusvara when followed by their plosive counterparts. <li>  Word-final consonantal /m/ is replaced by Anusvara',
        'Tibetan': 'The Sanskrit phonemes /c/, /ch/, /j/ and /jh/ are mapped to consonants TSA ཙ , TSHA ཚ, DZA ཛ, DZHA ཛྷ, respectively (according to Tibetan conventions). Tibetan Mark TSA -PHRU is used as Nukta. ',
        'Brahmi': 'The Segoe UI Historic font in Windows 10 supports a greater range of ligatures than Noto Sans Brahmi. If you do not see various Brahmi ligatures, it is possibly because of the lack of Segoe Historic UI in your system and Noto Sans Brahmi is being used as the replacement web font.',
        'Kaithi': 'Devanagari numerals have been used as Kaithi seems to lack a numeral set of its own. Devanagari Avagraha has been borrowed for the same reason as well. U+2E31 is used as the word separator.',
        'Vatteluttu': 'Vatteluttu is not yet enocoded in Unicode. Aksharamukha uses a hack-encoded font that uses the Tamil block to encode Vatteluttu. It does not contain /j/, /ś/, /ṣ/, /s/ and /h/ (as in Modern Tamil) in its reportoire as Grantha letters were usually augmented with Vatteluttu characters to represent them',
        'Tirhuta': 'The Nukta was used to extend the characters to create equivalents of South-Indic and other Nukta-ted characters that typically occur in North Indic scripts.',
        'Takri': 'Devanagari Avagraha has been used to denote Avagraha in Takri as well. The Nukta was used to extend the characters to create equivalents of South-Indic and other Nukta-ted characters that typically occur in North Indic scripts.',
        'Urdu': 'Urdu is an abjad. It amounts to short-vowels being not written and /v/ and /y/ also denoting long vowels. (The following assumes the consonats have an inherent /a/ like Indic scripts for illustration.). In the absense of short vowels, /ava/ can stand for /va/, /ū/, /o/ or /au/, /aya/ can stand for /ya/, /ī/, /e/ or /ai/. On the same note /kava/ could be /kava/, /kū/, /ko/, /kau/ and /kaya/ could be /kaya/, /kī/, /ke/ or /kai/, Thus /kayarala/ probably should be read /kerala/ and /hayadarābād/ as /haidarābād/. Additionally, the short-vowels (i/u) have to be guessed by context. As in North-Indic scripts, the Schwa deletion is also not shown explicitly. Ideally, /urdū/ should be written as /اُرْدُو/ but it is often written as /اردو/ (aradava). One should know that the first vowel is a short /u/, the schwa /a/ in r is deleted, and /va/ in this case denotes /ū/. Thus giving the reading <s>a</s><sup>u</sup>r<s>a</s>d<s>(ava)</s><sup>ū</sup>. /میں/ (mayaṃ) must be read m<s>(aya)</s><sup>e</sup>ṃ /meṃ/, /ہندوستان/ (hanadavasatāna) is read h<s>a</s><sup>i</sup>n<s>a</s>d<s>(ava)</s><sup>ū</sup>s<s>a</s>tān<s>a</s> /hindūstān/.<br/><br/> Aksharamukha approximates the Arabic-specific consonants to their nearest Indic counterparts and Hamza is shown with an underscore. Ayin is mapped to /a/. Fathatan becomes just an /n/.',
        'Tagalog': 'In Phillippine scripts, /i/ denotes both /i/ and /e/ and /u/ denotes both /u/ and /o/.',
        'Tagbanwa': 'In Phillippine scripts, /i/ denotes both /i/ and /e/ and /u/ denotes both /u/ and /o/.',
        'Buhid': 'In Phillippine scripts, /i/ denotes both /i/ and /e/ and /u/ denotes both /u/ and /o/.',
        'Hanunoo': 'In Phillippine scripts, /i/ denotes both /i/ and /e/ and /u/ denotes both /u/ and /o/.',
        'Sundanese': '<b> Historic Orthography </b> <br/><br/> Sundanese had characters for the following: ṛ, ḷ and bha :: <span class="sundanese">ᮻ ᮼ ᮽ</span>, but they are not in vogue any more. By default, Aksharamukha does not use these characters. They are replaced by their closest approximations: reu, leu and ba :: <span class="sundanese">ᮛᮩ ᮜᮩ ᮘ</span>. The historic characters are used only if the <i>preserve script</i> option is enabled. <br/><br/> <b>Historic Conjuncts</b> <br/><br/> Sundanese also had subjointed version of ma and wa, and also final-consonantal form for /k/ and /m/. For instance, <span class="sundanese">ᮊᮬ /kma/,  ᮊᮭ /kva/, ᮃᮾ /ak/, ᮃᮿ /am/ </span> as opposed to <span class="sundanese"> ᮊ᮪ᮙ, ᮊ᮪ᮝ, ᮃᮊ᮪ and ᮃᮊ᮪.</span>This can be manually enabled in the coverter.<br/><br/>',
        'Limbu': '<b> Mukhphreng and Kemphreng </b><br/><br/> The Glottal Stop (Mukhphreng) is transliterated using ʔ and the Kemphreng (Vowel Lengthening Mark), when ocurring with vowels other than /i/ and /u/ is denoted by ꞉ U+A789.<br/><br/> <b> Historic Orthography </b> <br/><br/> Limbu had characters for the following: jha ña ṣa ṃ :: <span class="limbu">ᤉ ᤊ ᤚ ᤲ</span>, but they are not in vogue any more. By default, Aksharamukha does not use these characters. They are replaced by their closest approximations: ja na śa ṅ :: <span class="limbu">ᤈ ᤏ ᤙ ᤱ</span>. The historic characters are used only if the <i>preserve script</i> option is enabled. <br/><br/> <b>Limbu Devanagari Transliteration Convention</b> <br/><br/> Limbu has its own convention, when transliterating to Devanagari. It uses vowels with Nuktas and Visarga to denote the vowel-lengthening. For instance,  <span class="limbu"> ᤀᤧ ᤀᤨ ᤀᤧ᤺ ᤁᤧ ᤁᤨ ᤁᤧ᤺  </span> is transliterated as: <span class="limbudeva">ए़ ओ़ ए़ः के़ को़ के़ः  </span> instead of ऎ ऒ ऎ꞉ कॆ कॊ कॆ꞉. The above sample text would be rendered as <br/><br/> <span class="limbudeva">आङ्गाॽ पेन्सःन् के़लःम्बाॽ मनाआ॥ आहिम् फुङ्ले़ङ्, आङ्गाॽ आत्तिन्नाङ् साम्‌योनिबा, साम्‌योथिम्हाॽ नसाःन् मे़न्जोक्नाबा आ॥ थिक्‌येम् किप्मा केघुबा तुक्माल्ले याङ्साङ्, सिदाबाङ्दाॽ मे़त्छिङ्से़ पेगाङ्साङ् मे़न्नूबा कर ये़सुमाङ्ओ नसान् चाेःक् हेम्तुङाङ्धो आङ्गा वेत्ताङ् बारो॥ - लाल बहादुर लिम्बु. कङ् नुसियेक्पा याक्पङ्गे़म्बा सेसे चुम्लुङ् कालेम्पोङ् बा चइत्‌रो॥ आल्लबा ये़त्छिॽगेम्पा सेसे चुम्लुङ् ११ अक्तुबर २०१४ सिलिगुदि ५०० मनालम्मो पाेःङ्ल पत्लो॥</span><br/><br/>The converter applies this convention if this option is selected.  <br/><br/> <b>SAI-I for Vowel Legnth</b><br/><br/> Limbu has two orthographic conventions. One that uses the SA-I to denote vowel-lengthening and final-forms for the regular vowel - <span class="limbu">ᤁᤢᤴ /kun/ vs ᤁᤢᤏ᤻ /kūn/</span>. In the latter, the vowel-lengthening is explicitly shown using Kemphreng - <span class="limbu">ᤁᤢᤴ /kun/ vs ᤁᤢ᤺ᤴ /kūn/</span>. Aksharamukha by default uses the latter but you can also select the first orthography.',
        'Lao': 'Lao lacks several consonants required to accurately write Pali properly  and therefore transliteration of Pali to Sanskrit is lossy with several inconsistent approximations. Non-Brahmic lao-specific consonants are sometimes used in transcribing Pali, particularly /ດ/, /ບ/, /ຟ/ and  /ຮ/. The first three are transliterated using the Nukta as /d̈/, /p̈/ and /b̈/, and the last one is mapped to /ṟ/. As noted, earlier there conventions are pretty inconsistent. Sometimes, /ດ/ is used to mark gemination but other times gemination is indicated by plain duplication of consonants, even within the same text. For instance, <a href="http://www.watmai.com.au/373837713732375437693732374537713737.html">here</a> you find: <br/><br/> ອິຕິປິໂສ  ພະຄະວາ  ອະຣະຫັງສັມມາສັມພຸທໂທ  ວິຊຊາຈະຣະນະສັມປັນໂນ ສຸຄະໂຕ  ໂລກະວິທູ  ອະນຸຕຕະໂຣ  ປຸຣິສະທັມມະສະຣະຖີ  ສັຕຖາເທວະມະນຸສສານັງ<br/> itipiso bagavā arahaṅsammāsambuddo vijjācaranasampanno sugato lokavidū anuttaro purisadammasarathī satthādevamanussānaṅ <br/><br/> ອິຕິປິໂສ ພະຄະວາ ອະຣະຫັງສັມມາ ສັມພຸດໂທ ວິດຊາຈາຣະນະສັມປັນໂນ ສຸຄະໂຕ ໂລກະວິທູ ອະນຸດ ຕະໂລ ປຸຣິສະທັມມັດສະຣະຖີ ສັດຖາເທວະມະນຸດສານັງ  <br/> itipiso bagavā arahaṅsammā sambud̈do vid̈jācāranasampanno sugato lokavidū anud̈ talo purisadammad̈sarathī sad̈thādevamanud̈sānaṅ  <br/><br/> On a similar note, /r/ and /l/ are sometimes mixed as in some cases /ṟ/ is used for /r/ as in /ຮັກສາ/ (ṟaksā). /p̈b/ is also used to denoted geminated /b/, apart from /bb/ as in /ສັບເພ/ (sap̈be) and /ສັພເພ/ (sabbe). And ຳ is occasionally also used to denote gemination of /m/ as in /ສໍາມາສໍາພຸດໂທ/ (sāṃmāsāṃbud̈do) as in <a href="http://yarkhu.blogspot.com/2017/08/blog-post.html">here</a>. /cha/ is also replaced by /sa/ as in /ຄັດ​ສາ​ມິ/ (gacchāmi) or / ຄັສສະມິ/ (gasami)  for /gacchāmi/ even /gacsami/ mi. and ຍ /ñ/ is used for both /ñ/ and /y/ as in /ñakkha/ instead of /yakkha/ (Since /ຍ/ is technically cognate to brahmic /ya/ and only later came to represent /ñ/ phonetically) and /kg/ can also represetn /gg/ . REfere hre for mroe quirks of Laotian Pali http://www.pali.pratyeka.org/#Laoaccent <br/><br/>Maha Sila Viravong made additiions to the Lao script to express Pali phonology properly by having one-to-one correspondance with the Brahmic set of consonants. Please refer to Lao (Pali) for further information. <h5> Lao nativation </h5> The following are applied to the output based on the above Laotians conventions <br/><br/> 1. /cha/ is mapped to /sa/ <br/> 2. Both /ya/ and /ña/ are mapped to /ña/ (ຍ) <br/> 2. /d̈/ is used to mark gemination for /d/, /t/, /th/ and /s/ <br/> 3. /p̈/ is used as the gemination marker for /p/ and /b/',
        'LaoPali': 'Unlike its neighboring scripts that imported the entire “Indic” consonant repertoire,Lao lacks several characters that are required to accurately express the phonology of Pali/Sanskrit. Modern Lao cannot faithfully represent Pali words, and by extension cannot transcript religious texts faithfully. <br/> <br/> To enable the Lao script to completely and faithfully express the Pali language and also write Indic loan words with proper etymological spelling, Buddhist scholars tried to implement a script reform. In the 1930s Buddhist scholar Maha Sila Viravong at the initiation of the Buddhist Institute in Vientiane and approved by the Buddhist Academic Council, added an additional set of characters to support Pali (and also Sanskrit) by filling in the missing gaps. The Buddhist Institute using the expanded script published several books such as Dhammapada and Pali Grammar. Their aim was to make Pali more accessible to the common public. But the addition met with little widespread support and finally by 1975, these additional characters were mostly out of use. There is a revived interest in the characters and a few modern publications have been printed using them in an attempt to propose an etymological orthography for Lao. Please refer to the Unicode <a href="https://www.unicode.org/L2/L2017/17106r-lao-for-pali.pdf">proposal</a> for further information. <br/><br/> <b> Lao Orthography </b> <br/><br/> This applies the following conventions: <br/><br/> 1. Replace Anusvara with /ṅ/ <br/> 2. Show the inherent /a/ explicitly. <br/><br/> The sample pali text would be rendered as: <br/><br/> <span class="laopali"> ເຍ ຘັມມາ ເຫຕຸປປະຠະວາ ເຕສັງ ເຫຕຸງ ຕະຖາຄະໂຕ ອາຫະ ຯ <br/> ເຕສັຎຈະ ໂຍ ນິໂຣໂຘ ເອວັງ ວາທີ ມະຫາສະມະໂຓ </span>',
        'Thai': '<b> Thai Orthography </b> <br/><br/> This applies the following conventions: <br/><br/> 1. Replace Anusvara with /ṅ/ <br/> 2. Show the inherent /a/ explicitly. <br/><br/> The sample pali text would be rendered as: <br/><br/> <span class="thai"> เย ธัมมา เหตุปปะภะวา เตสัง เหตุง ตะถาคะโต อาหะ ฯ <br/> เตสัญจะ โย นิโรโธ เอวัง วาที มะหาสะมะโณ ๚ </span>',
        'WarangCiti': 'Both aspiration and long /a/ is denoted by adding /h/. Given that the consonants have an inherent vowel coupled and a functional Virama is not present, a sequence like <span class="warangciti">𑣌𑣙</span> can stand for /kah/, /kaha/, /kha/, or /kā/ depending on the context. <span class="warangciti">𑣄</span> is actually the glottal stop /ʔ/ but seems to traditionally be mapped to Visarga.'
      },
      textNative: {
        'Buginese': 'ᨔᨗᨔᨗᨊᨗᨊ ᨑᨘᨄ ᨈᨕᨘ ᨑᨗ ᨍᨍᨗᨕᨂᨗ ᨑᨗᨒᨗᨊᨚᨕᨙ ᨊᨄᨘᨊᨕᨗ ᨆᨊᨙᨂᨗ ᨑᨗᨕᨔᨙᨂᨙ ᨕᨒᨙᨅᨗᨑᨙ᨞ ᨊᨄᨘᨊᨕᨗ ᨑᨗᨕᨔᨙᨂᨙ ᨕᨀᨒᨙ᨞ ᨊᨄᨘᨊᨕᨗ ᨑᨗᨕᨔᨙᨂᨙ ᨕᨈᨗ ᨆᨑᨙᨊᨗ ᨊ ᨔᨗᨅᨚᨒᨙ ᨅᨚᨒᨙᨊ ᨄᨉ ᨔᨗᨄᨀᨈᨕᨘ ᨄᨉ ᨆᨔᨒᨔᨘᨑᨙ᨞',
        'Telugu': 'సిద్ధార్ధుడు కపిలవస్తు దేశానికీ చెందిన లుంబిని పట్టణంలో జన్మించాడు. భౌగొళికంగా ఈ ప్రాంతం ప్రస్తుత నేపాల్ దేశంలో ఉంది. కానీ చారిత్రకంగా ఈ ప్రాంతం ప్రాచీన భారతదేశంలోకి వస్తుంది. గౌతమ అనునది సిద్ధార్ధుని ఇంటి పేరు కాదు సిద్ధార్ధుని పెంచిన తల్లి గౌతమి. అందుకు గాను అతనికి ఆ పేరు వచ్చింది. తండ్రి శుద్ధోధనుడు, తల్లిమహామాయ (మాయాదేవి, కోళియన్ దేశపు రాకుమారి). సిద్దార్డుడు గర్భమందున్నప్పుడు, మాయాదేవి, ఒక ఆరు దంతముల ఏనుగు తన గర్భములోకి కుడి వైపు నుండి ప్రవేశించినట్లుగా ఒక స్వప్నమందు దర్శించింది. అది జరిగిన పది చంద్ర మాసముల తర్వాత సిద్ధార్డుడు జన్మించెను. శాక్యవంశాచారము ప్రకారం, గర్భావతిగానున్న మాయాదేవి, ప్రసవానికి తన తండ్రిగారింటికి బయలుదేరింది. కానీ మార్గమధ్యంలో, లుంబిని అనే ప్రాంతంలో ఒక సాలవృక్షం క్రింద ఒక మగ బిడ్డను ప్రసవించింది.',
        MeeteiMayek: 'ꯄꯥꯎꯟꯗꯦꯁꯟ ꯗꯦ ꯑꯁꯤ ꯇꯁꯦꯡꯕꯗꯤ ꯁꯦꯞꯇꯦꯝꯕꯔ ꯒꯤ ꯇꯥꯡ ꯲꯱ ꯗꯥ ꯗꯧꯒꯗꯕꯅꯤ ꯑꯗꯨꯕꯨ ꯂꯩꯕꯥꯛꯀꯤ ꯑꯣꯏꯕ ꯏꯁꯨ ꯑꯃꯥ ꯂꯩꯕꯅꯥ ꯅꯨꯃꯤꯠ ꯑꯁꯤꯃꯛꯇꯗꯥ ꯄꯥꯡꯊꯣꯛꯄꯗꯨ ꯉꯝꯖꯗ꯭ꯔꯦ꯫ ꯃꯁꯤꯅꯥ ꯃꯔꯝ ꯑꯣꯏꯔꯒꯥ ꯁꯤꯜꯂꯤ ꯂꯥꯡꯂꯤꯕ ꯁꯤꯡꯗ ꯄꯦꯟꯗꯕ ꯍꯥꯏꯕꯗꯨ ꯑꯣꯏꯍꯜꯂꯦ ꯑꯗꯨꯝ ꯑꯣꯏꯅꯃꯛ ꯊꯧꯔꯝ ꯑꯁꯤꯗꯤ ꯁꯤꯟꯗꯕ ꯌꯗꯕ ꯑꯣꯏꯕꯅ ꯃꯇꯝ ꯈꯔꯥ ꯌꯩꯊꯔꯥꯒ ꯑꯣꯏꯅ ꯁꯤꯜꯂꯒꯅꯤ꯫ ꯇꯥꯡ ꯲꯲/꯲꯴ ꯑꯁꯤ ꯑꯣꯖꯥ ꯇꯞꯇꯥ ꯒꯤ ꯏꯁꯩꯒꯤ ꯊꯧꯔꯝ ꯇꯥꯡ ꯲꯳ ꯗꯥ ꯍꯠꯇꯥ ꯀꯥꯡꯖꯩꯕꯨꯡ ꯗꯥ ꯂꯩꯕꯅꯥ ꯄꯣꯊꯥꯕꯥꯒꯤ ꯃꯗꯝ ꯍꯥꯏꯕꯗꯨ ꯑꯣꯏꯔꯦ꯫ ꯃꯊꯡꯒꯤ ꯅꯨꯃꯤꯠ ꯇꯥꯡ ꯲꯵ ꯑꯁꯤꯅꯥ ꯑꯣꯖꯥ ꯇꯞꯇꯥ ꯕꯨ ꯋꯍꯡ ꯍꯡꯒꯗꯧꯔꯤꯕ ꯏꯌꯥꯝꯕꯥ ꯔꯥꯖ ꯅꯣꯡꯊꯣꯝꯕꯝ ꯒꯤ ꯏꯝꯄꯥꯛ ꯇꯤ ꯘꯤ ꯒꯤ ꯃꯥꯅꯨꯡ ꯍꯨꯠꯅꯥ ꯒꯤ ꯊꯧꯔꯝ ꯂꯩꯕꯅꯥ ꯅꯨꯃꯤꯠꯁꯤꯃꯥꯁꯨ ꯌꯥꯗ꯭ꯔꯦ꯫ ꯃꯔꯝ ꯑꯁꯤꯅ ꯂꯥꯛꯂꯤꯕ ꯁꯦꯞꯇꯦꯝꯕꯔ ꯒꯤ ꯇꯥꯡ ꯲꯶ ꯂꯩꯕꯥꯛꯄꯣꯛꯄ ꯅꯨꯃꯤꯠ ꯑꯁꯤꯗ ꯄꯥꯡꯊꯣꯛꯑꯒꯅꯤ꯫ ꯃꯤꯌꯥꯝ ꯈꯨꯗꯤꯡꯃꯛ ꯑꯆꯤꯟꯕ ꯀꯌꯥ ꯀꯥꯏꯊꯣꯛꯄꯤꯗꯨꯅꯥ ꯑꯁꯤꯒꯨꯝꯕ ꯊꯧꯔꯝ ꯑꯁꯤꯕꯨ ꯁꯔꯨꯛ ꯌꯥꯕꯤꯗꯨꯅꯥ ꯃꯥꯄꯨꯡ ꯐꯥꯍꯟꯕꯤꯌꯨ ꯍꯥꯏꯅ ꯍꯥꯏꯖꯔꯤ꯫',
        Kannada: 'ಘಟನೆ ೧.ಕಪಿಲವಸ್ತುವಿನಲ್ಲಿ ಸಾಂಪ್ರದಾಯಿಕ ಸಮಾರಂಭವೊಂದು ಏರ್ಪಟ್ಟಿತು. ವ್ಯವಸಾಯದ ಕಾಲ ಪ್ರಾರಂಭವಾದಾಗ, ಕೃಷಿ ಆರಂಭೋತ್ಸವದಲ್ಲಿ ಭಾಗವಹಿಸಲು, ಸಿದ್ದಾರ್ಥನಿಗೆ ರಾಜ ಶುದ್ಧೋದನ ಹೇಳಿದನು. ಅದರಂತೆ ಬಂಗಾರದ ನೇಗಿಲಿಗೆ, ಸುಂದರವಾದ ಶ್ವೇತವರ್ಣದ ಎತ್ತುಗಳನ್ನು ಕಟ್ಟಿ, ಮುಂದುಗಡೆಯಲ್ಲಿ ರಾಜಕುಮಾರ ಸಿದ್ದಾರ್ಥ ನೆಲವನ್ನು ಉತ್ತನು. ನಂತರ ರಾಜಕುಮಾರ ಸಿದ್ದಾರ್ಥನ ಹಿಂದೆ ಸಾವಿರಾರು ಜನ ಉಳುಮೆ ಮಾಡುವುದರಲ್ಲಿ ಭಾಗವಹಿಸಿದರು. ಅವರೆಲ್ಲ ನೇಗಿಲಿನಿಂದ ನೆಲವನ್ನು ಬಗೆದೊಡನೆ, ನೆಲದಿಂದ ಅನೇಕ ಕ್ರಿಮಿ ಕೀಟಗಳು ಹೊರಗೆ ಬರಲಾರಂಭಿಸಿದವು. ಅವನ್ನು ಕಂಡು ಅಂತರಿಕ್ಷದಲ್ಲಿ ಹಾರಾಡುತ್ತಿದ್ದ ಪಕ್ಷಿಗಳು ಬಂದು ಅವುಗಳನ್ನು ಕೊಕ್ಕಿನಲ್ಲಿ ಕುಕ್ಕಿ ತಿನ್ನುವುದನ್ನು ಕಂಡಾಗ ರಾಜಕುಮಾರ ಸಿದ್ದಾರ್ಥನ ಮನದಲ್ಲಿ ವೇದನೆ ಉಂಟಾಯಿತು. ಆದರದನ್ನು ಅವನು ಯಾರಿಗೂ ತಿಳಿಸಲಿಲ್ಲ.ಘ ಟನೆ ೨. ಒಂದು ದಿನ ಸೋದರ ದೇವದತ್ತನು ಉದ್ಯಾನವನದಲ್ಲಿ ಹಾರಾಡುತ್ತಿದ್ದ ಹಂಸಪಕ್ಷಿಗೆ ಬಾಣ ಪ್ರಯೋಗ ಮಾಡಿದನು.',
        Sinhala: 'පාලි ධර්ම ග්‍රන්ථ වල බුදුරජාණන්වහන්සේගේ නියම ඉගැන්වීම් ඒ ආකාරයෙන්ම සඳහන් වන බව බොහෝ පඬිවරුන්ගේ විශ්වාසයයි. එහෙත් මහායාන වල මුලාරම්භය මුල් බුදුදහමේ අඩංගු වුවද, මහායාන සුත්‍ර බුද්ධ දේශනා ලෙස නොසැලකේ. නමුත් කිසිවෙකුත් බුදුරජාණන් වහන්සේ සැබෑ ලෙස දේශනා කළේ මේ කරුණු යැයි නිසැකයෙන් ම කීමට අපොහොසත් හෙයින් මහායාන ලියවිලි වල සඳහන් දෑ බුදුරජාණන් වහන්සේගේ මුල් දේශනා ලෙස දක්වා ඇත. නමුත් බටහිර වියතුන් බොහෝ දෙනෙක් පිළිගන්නේ ගෞතම බුදුරජාණන් වහන්සේගේ ඉගැන්වීම් සත්‍ය වශයෙන්ම සඳහන් වන්නේ පාලිධර්ම ග්‍රන්ථ වල බවයි. බුදුරජාණන් වහන්සේ යනු කවුද ? උන්වහන්සේගේ ඉගැන්වීම් මොනවාද? යන්න විවිධ වූ අර්ථ විවරණ වලින් දැනගත හැකිය. උන්වහන්සේ උත්තම ස්ථානයකට පත්වූ මනුෂ්‍යයෙක්',
        Assamese: 'সিদ্ধাৰ্থৰ পিতৃ আছিল শাক্য বংশীয় ৰজা শুদ্ধোধন। মাতৃ মায়াদেৱী। মায়াদেৱী কপিলাবস্তুৰ পৰা পিতৃৰ ৰাজ্য যোৱাৰ পথত লুম্বিনি গ্ৰামত (বৰ্তমান নেপালৰ অন্তৰ্গত) সিদ্ধাৰ্থক জন্ম দিছিল। তেওঁৰ জন্মৰ সপ্তম দিনাখনেই মায়াদেৱীৰ জীৱনাবসান ঘটে। পাছত তেওঁ মাহীমাক গৌতমীৰ হাতত লালন পালন হয়। ধাৰণা কৰা হয় তেওঁৰ নামৰ "গৌতম" অংশটি মাহীমাকৰ নামৰ পৰাই আহিছে। আকৌ কিছুমানৰ মতে এইটো তেখেতসকলৰ বংশানুক্ৰমিক নাম। জন্মৰ পঞ্চম দিনা তেখেতৰ পিতৃয়ে ৮ জন জ্ঞানী ব্যক্তিক সদ্যোজাত শিশুটিৰ নামকৰণ আৰু ভৱিষ্যত গণনা কৰাৰ বাবে নিমন্ত্ৰণ কৰিছিল। তেতিয়া তেওঁৰ নাম সিদ্ধাৰ্থ ৰখা হয় - সিদ্ধাৰ্থ শব্দটোৱে "সিদ্ধিলাভ কৰা, বা উদ্দেশ্য সফল" হোৱা বুজাই। তেখেতসকলৰ মাজৰ এজনে লগতে কয় যে, ৰাজকুমাৰ এদিন সত্যৰ সন্ধানত বাহিৰলৈ ওলাই যাব আৰু বোধিপ্ৰাপ্ত হব। এজন ৰাজপুত্ৰ হিচাপে সিদ্ধাৰ্থই বিভিন্ন শাখাত শিক্ষা লাভ কৰিছিল।',
        Bengali: 'বিভিন্ন পরস্পরবিরোধী ঐতিহ্যশালী জীবনীগ্রন্থগুলি সিদ্ধার্থ গৌতমের জীবনীর উৎস। এর মধ্যে দ্বিতীয় শতাব্দীতে অশ্বঘোষ দ্বারা রচিত বুদ্ধচরিত নামক মহাকাব্যটি বুদ্ধের প্রথম পূর্ণ জীবনীগ্রন্থ। তৃতীয় শতকে রচিত ললিতবিস্তার সূত্র গৌতম বুদ্ধের জীবনী নিয়ে লিখিত পরবর্তী গ্রন্থ। সম্ভবতঃ চতুর্থ শতাব্দীতে রচিত মহাসাঙ্ঘিক লোকোত্তরবাদ ঐতিহ্যের মহাবস্তু গ্রন্থটি অপর একটি প্রধান জীবনী গ্রন্থ হিসেবে পরিগণিত হয়। তৃতীয় থেকে ষষ্ঠ শতাব্দীতে রচিত ধর্মগুপ্তক ঐতিহ্যের অভিনিষ্ক্রমণ সূত্র গ্রন্থটি বুদ্ধের একটি বিরাট জীবনীগ্রন্থ। সর্বশেষে পঞ্চম শতাব্দীতে রচিত বুদ্ধঘোষ রচিত থেরবাদ ঐতিহ্যের নিদানকথা উল্লেখ্য। ত্রিপিটকের অংশ হিসেবে জাতক মহাপদন সূত্ত ও আচারিয়াভুত সুত্তে বুদ্ধের পূর্ণ জীবনী না থাকলেও কিছু নির্বাচিত অংশ রয়েছে।।',
        Gujarati: 'ચલિત માન્યતાઓ પ્રમાણે સિદ્ધાર્થ ગૌતમનો જન્મ મૌર્ય રાજા અશોકના શાસનના ૨૦૦ વર્ષ પહેલા થયો હતો. તેઓનો જન્મ પ્રાચીન ભારતના લુમ્બિનિમાં, જે આજે નેપાળમાં છે, થયો હતો. રાજા સુધોધન તેમના પિતા અને રાણી મહામાયા તેમના માતા હતા. તેમનાં જન્મ વખતે અથવા તેના થોડાજ સમય બાદ માતા મહામાયાનું અવસાન થયું હતું. એમના નામકરણ વખતે ઘણાં વિદ્વાનોએ ભવિષ્યવાણી કરી હતી કે એ મહાન રાજા અથવા મહાન સદ્પુરુષ બનશે. એક રાજકુમાર હોવાથી સિદ્ધાર્થ ગૌતમનો વૈભવી રીતે ઉછેર થયો હતો. ૧૬ વર્ષની વયે તેમનાં લગ્ન યશોધરા સાથે કરવામાં અવ્યા હતા. સમય વહેતા તેમને રાહુલ નામના પુત્રનો જન્મ થયો. જે જોઈએ એ બધું જ હોવા છતાં તેમને એવું લાગતું કે ભૌતિક સુખ જીવનનું સર્વોચ્ચ લક્ષ્ય નથી.',
        Malayalam: 'ധർമ്മപദത്തിൽ ഇരുപത്തിനാലദ്ധ്യായങ്ങളിൽ ബുദ്ധമതത്തിന്റെ സാരം അടങ്ങിയിരിയ്ക്കുന്നു. ബുദ്ധമതം എന്നു വെച്ചാൽ ബുദ്ധൻ പ്രസംഗിച്ച പ്രകാരത്തിലുള്ള തത്ത്വങ്ങളും ആദികാലങ്ങളിൽ ധർമ്മം എന്ന വിശേഷനാമത്തോടുകൂടിയുള്ള മതവുമാകുന്നു. "പാപത്തെ ദൂരെ ത്യജിക്കുകയും, പുണ്യത്തെ എല്ലായ്പോഴും ചെയ്യുകയും, പ്രാണികളിൽ സ്നേഹം, സത്യം, ക്ഷമ, ശുദ്ധി, ഇവയോടും കൂടി ഇരിയ്ക്കുകയുമാകുന്നു" ധർമ്മം എന്നതിന്റെ സാരാർത്ഥം എന്ന് അശോകൻ പറയുന്നു. ബുദ്ധമത തത്ത്വചിന്തയുടെ ഒരു പ്രധാനപ്പെട്ട തത്ത്വമാണ് ചതുര സത്യങ്ങൾ എന്നറിയപ്പെടുന്നത്. ദുഃഖം, ദുഖ കാരണം, ദുഖനിവാരണം, ദുഖ നിവാരണമാർഗ്ഗം എന്നിവ ചതുര സത്യങ്ങളായി അറിയപെടുന്നു. ക്രിസ്താബ്ദത്തിന്ന് 563 കൊല്ലം മുന്പ്, കപിലവസ്തുവിനു സമീപം ലുംബിനി ഉപവനത്തിൽ ജനിച്ചു. എന്നിരുന്നാലും ശ്രീബുദ്ധന്റെ ജനനത്തെപ്പറ്റി ആധികാരികമായ രേഖകൾ ഇല്ല. മിക്ക ചരിത്രകാരന്മാരും പല അവലംബം ഉപയോഗിച്ച് വ്യത്യസ്തമായ കാലഘട്ടങ്ങളാണ് സൂചിപ്പിക്കുന്നത്. ക്രി.മു. 400 ന് മുന്നായിരിക്കണം അദ്ദേഹം ജനിച്ചത് എന്ന് ഒരു വിഭാഗം വിചാരിക്കുന്നു.',
        Oriya: 'ଗୌତମ ବୁଦ୍ଧଙ୍କ ପରିନିର୍ମାଣର ଅଳ୍ପ କାଳ ମଧ୍ୟରେ ବୌଦ୍ଧ ଧର୍ମ ସମଗ୍ର ଭାରତବର୍ଷରେ ପ୍ରସାରଲାଭ କରିଥିଲା । ବିଶେଷତଃ ଖ୍ରୀ.ପୂ. ତୃତୀୟ ଶତାବ୍ଦୀରେ ମୌର୍ଯ୍ୟ ସମ୍ରାଟ ଅଶୋକଙ୍କ ପୃଷ୍ଠପୋଷକତାରେ ବୌଦ୍ଧ ଧର୍ମ କେବଳ ଭାରତରେ ନୁହେଁ, ଭାରତ ବାହାରେ ଯଥା, ପଶ୍ଚିମରେ ଗ୍ରୀସ ଦେଶଠାରୁ ପୂର୍ବରେ ବ୍ରହ୍ମଦେଶ (ବର୍ତ୍ତମାନର ମିଆଁମାର) ଏବଂ ଦକ୍ଷିଣରେ ସିଂହଳ (ବର୍ତ୍ତମାନର ଶ୍ରୀଲଙ୍କା) ପର୍ଯ୍ୟନ୍ତ ପ୍ରସାରିତ ହୋଇଥିଲା । ଖ୍ରୀଷ୍ଟୀୟ ପ୍ରଥମ ଶତାବ୍ଦୀରେ କୁଶାଣ ବଂଶର ଶ୍ରେଷ୍ଠ ସମ୍ରାଟ କନିଷ୍କଙ୍କ ପ୍ରେରଣାରେ ବୌଦ୍ଧଧର୍ମ ଚୀନ, ତିବ୍ବତ, ଜାପାନ ପ୍ରଭୃତି ଦେଶରେ ପ୍ରଚାରିତ ହୋଇଥିଲା । ସପ୍ତମ ଓ ଅଷ୍ଟମ ଶତାବ୍ଦୀରେ କନୌଜର ରାଜା ହର୍ଷବର୍ଦ୍ଧନଙ୍କ ସାହାଯ୍ୟରେ ବୌଦ୍ଧଧର୍ମ ବିଶେଷ ଅଗ୍ରଗତି ଲାଭ କରିଥିଲା । ଏହିପରି ପୃଷ୍ଠପୋଷକତା ଲାଭକରି ବୌଦ୍ଧଧର୍ମ ପୃଥିବୀର ଏକ ମୂଖ୍ୟ ଧର୍ମରେ ପରିଣତ ହୋଇଥିଲା । ପ୍ରାଚୀନ ରାଜା ମହାରାଜାମାନଙ୍କଦ୍ଵାରା ଅତି ସୁନ୍ଦର କାରୁକାର୍ଯ୍ୟପୂର୍ଣ୍ଣ ଅସଂଖ୍ୟ ବୌଦ୍ଧଗୁମ୍ଫା, ସ୍ତୂପ, ଚୈତ୍ୟ, ବୌଦ୍ଧବିହାର ଓ ବୌଦ୍ଧମୂର୍ତ୍ତି ଗୁଡ଼ିକ ଭାରତର ବିଭିନ୍ନ ସ୍ଥାନରେ ନିର୍ମିତ ହୋଇଥିଲା, ଯାହା ବୌଦ୍ଧ ଧର୍ମର ପ୍ରଚାର ଏବଂ ପ୍ରସାର ଦିଗରେ ଯଥେଷ୍ଟ ସାହାଯ୍ୟ କରିଥିଲା । ସମ୍ରାଟ ଅଶୋକଙ୍କର ଅନୁଶାସନ ବୌଦ୍ଧଧର୍ମ ପ୍ରସାରର ଏକ ପ୍ରଧାନ କାରଣ ।',
        Gurmukhi: 'ਰਾਜਕੁਮਾਰ ਗੌਤਮ ਨੇ ਇੱਕ ਵਾਰ ਰੱਥ ਵਿੱਚ ਬੈਠ ਕੇ ਸੈਰ ਕਰਦੇ ਸਮੇਂ ਬੁੱਢੇ ਆਦਮੀ, ਰੋਗੀ ਅਤੇ ਮੁਰਦੇ ਨੂੰ ਦੇਖ ਕੇ ਇਹ ਅਨੁਭਵ ਕੀਤਾ ਕਿ ਸੰਸਾਰ ਦੁੱਖਾਂ ਦਾ ਅਤੇ ਮੁਸੀਬਤਾਂ ਦਾ ਘਰ ਹੈ ਅਤੇ ਜਨਮ ਲੈਣ ਵਾਲਾ ਕੋਈ ਵੀ ਵਿਅਕਤੀ ਬੁਢਾਪੇ, ਬਿਮਾਰੀ ਅਤੇ ਮੌਤ ਤੋਂ ਨਹੀਂ ਬਚ ਸਕਦਾ। ਫਿਰ ਗੌਤਮ ਨੇ ਇੱਕ ਪ੍ਰਸੰਨ ਚਿੱਤ ਸੰਨਿਆਸੀ ਦੇਖਿਆ, ਜੋ ਜੀਵਨ ਅਤੇ ਮਰਨ ਦੇ ਬੰਧਨਾਂ ਤੋਂ ਮੁਕਤੀ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਸੰਸਾਰ ਤਿਆਗ ਕੇ ਸੱਚ ਦੀ ਖੋਜ ਵਿੱਚ ਲੱਗਾ ਹੋਇਆ ਸੀ, ਇਨ੍ਹਾਂ ਚਾਰ ਦਿਸ਼ਾਵਾਂ ਦਾ ਗੌਤਮ ਬੁੱਧ ਦੇ ਮਨ ‘ਤੇ ਏਨਾ ਡੂੰਗਾ ਪ੍ਰਭਾਵ ਪਿਆ ਕਿ ਉਨ੍ਹਾਂ ਨੇ ਸੱਚੇ ਗਿਆਨ ਦੀ ਖੋਜ ਲਈ ਘਰ ਨੂੰ ਤਿਆਗਣ ਦਾ ਦ੍ਰਿੜ੍ਹ ਨਿਸ਼ਚਾ ਕਰ ਲਿਆ। ਇਕ ਰਾਤ ਗੌਤਮ ਆਪਣੇ ਪੁੱਤਰ, ਪਤਨੀ ਅਤੇ ਮਹਿਲ ਨੂੰ ਛੱਡ ਕੇ ਆਪਣੇ ਘੋੜੇ ਕੰਥਕ ‘ਤੇ ਸਵਾਰ ਹੋ ਕੇ ਸੱਚਾਈ ਦੀ ਖੋਜ ਵਿੱਚ ਚੁੱਪ-ਚਾਪ ਘਰੋਂ ਚਲੇ ਗਏ। ਯੋਗ ਗੁਰੂ ਦੀ ਭਾਲ ‘ਚ ਪਹਿਲਾਂ ਰਾਜ ਗ੍ਰਹਿ ਸ਼ਹਿਰ ਦੇ ਅਲਾਰ ਅਤੇ ਕੁਦਰਨ ਵਿਦਵਾਨਾਂ ਪਾਸੋਂ ਸਿੱਖਿਆ ਪ੍ਰਾਪਤ ਕੀਤੀ। ਫਿਰ ਗਯਾ ਨੇੜੇ ਪੰਜ ਸਾਥੀਆਂ ਨਾਲ ਮਿਲ ਕੇ ਘੋਰ ਤਪੱਸਿਆ ਕੀਤੀ ਪਤੂ ਮਨ ਨੂੰ ਸ਼ਾਂਤੀ ਨਾ ਮਿਲਣ ਕਾਰਨ ਤਪੱਸਿਆ ਦਾ ਰਾਹ ਛੱਡ ਦਿੱਤਾ। ਫਿਰ ਗਯਾ ਵਿਖੇ ਨਿਰੰਜਨਾ ਨਦੀ ਦੇ ਕੰਢੇ ‘ਤੇ ਪਿੱਪਲ ਦੇ ਇੱਕ ਦਰੱਖਤ ਹੇਠ ਸਮਾਧੀ ਲਾ ਕੇ ਉਹ ਬੈਠ ਗਏ। ਗੌਤਮ ਸੱਤ ਦਿਨ ਅਤੇ ਸੱਤ ਰਾਤਾਂ ਅਖੰਡ ਸਮਾਧੀ ਵਿੱਚ ਸਥਿਰ ਰਹੇ।',
        Santali: 'ᱥᱟᱱᱛᱟᱲᱤ ᱯᱟᱹᱨᱥᱤ ᱨᱮᱱᱟᱜ ᱪᱤᱠᱤ ᱵᱟᱝ ᱛᱟᱸᱦᱮᱠᱟᱱᱛᱮ ᱢᱤᱫ ᱡᱚᱠᱷᱚᱡ ᱵᱟᱝᱞᱟ, ᱫᱮᱵᱷᱱᱟᱜᱨᱤ, ᱨᱳᱢᱟᱱ, ᱩᱲᱤᱭᱟ ᱪᱤᱠᱤ ᱛᱮᱜᱮᱠᱚ ᱚᱞᱮᱫ ᱛᱟᱸᱦᱮᱱᱟ᱾ ᱚᱱᱟ ᱠᱷᱟᱹᱛᱤᱨᱛᱮ ᱥᱟᱱᱛᱟᱲᱤ ᱥᱟᱶᱦᱮᱫ ᱵᱟᱝ ᱞᱟᱦᱟᱜ ᱠᱟᱱ ᱛᱟᱦᱮᱸᱠᱟᱱᱟ ᱟᱨ ᱟᱭᱢᱟ ᱪᱤᱠᱤᱛᱮ ᱚᱞᱚᱜ ᱠᱷᱟᱹᱛᱤᱨ ᱪᱷᱟᱢ ᱪᱷᱟᱹᱛᱩᱨ ᱚᱵᱚᱥᱛᱷᱟ ᱛᱟᱸᱦᱮᱠᱟᱱᱟ᱾ ᱮᱴᱟᱜ ᱪᱤᱠᱤ ᱛᱮ ᱥᱟᱱᱛᱟᱲᱤ ᱚᱞᱚᱜ ᱠᱟᱨᱚᱱᱛᱮ ᱯᱩᱥᱴᱟᱹᱣ ᱛᱮᱸᱦᱚ ᱵᱟᱝ ᱚᱞᱚᱜ ᱠᱟᱱ ᱛᱟᱸᱦᱮ ᱠᱟᱱᱟ᱾ ᱚᱱᱟᱠᱚ ᱫᱤᱥᱟᱹ ᱠᱟᱛᱮᱡ ᱜᱮ ᱱᱚᱣᱟ ᱫᱷᱟᱹᱨᱛᱤ ᱠᱷᱚᱡᱜᱮ ᱩᱱᱤᱫᱚ ᱤᱝᱨᱮᱡᱤ ᱑᱙᱒᱕ ᱥᱮᱨᱢᱟᱨᱮ ᱚᱞ ᱪᱤᱠᱤ ᱪᱤᱭᱟᱹ ᱠᱮᱫᱟ᱾ ᱚᱞᱚᱜ ᱵᱚᱸᱜᱟ ᱵᱤᱫᱩ ᱪᱟᱸᱫᱟᱱ ᱩᱭᱦᱟᱹᱨᱛᱮ ᱚᱞ ᱪᱤᱠᱤ ᱥᱤᱨᱡᱟᱹᱣ ᱟᱠᱟᱫ-ᱟ ᱢᱮᱱᱛᱮᱭ ᱞᱟᱹᱭ ᱟᱠᱟᱫ ᱟᱭ ᱯᱚᱸᱰᱮᱛ ᱨᱟᱹᱜᱷᱩᱱᱟᱛ ᱢᱩᱨᱢᱩ᱾ ᱢᱤᱫ ᱥᱟᱭ ᱜᱮᱞ ᱢᱚᱬᱮ ᱪᱮᱛᱟᱱ ᱯᱚᱛᱚᱵ ᱠᱚᱭ ᱚᱞ ᱟᱠᱟᱫᱟ ᱨᱟᱹᱜᱷᱩᱱᱟᱛ ᱢᱩᱨᱢᱩ᱾ ᱢᱚᱭᱩᱨᱵᱷᱚᱸᱡ ᱢᱚᱦᱟᱥᱚᱵᱷᱟᱨᱮ ᱨᱟᱹᱜᱷᱩᱱᱟᱛ ᱢᱩᱨᱢᱩ ᱫᱚ ᱜᱩᱨᱩ ᱜᱚᱢᱠᱮ ᱩᱯᱟᱹᱫᱷᱤ ᱦᱚᱸᱭ ᱧᱟᱢ ᱞᱮᱫ-ᱟ᱾ ᱡᱷᱟᱲᱠᱷᱚᱸᱰ ᱨᱮᱭᱟᱜ ᱨᱟᱸᱪᱤ ᱤᱩᱱᱤᱵᱷᱟᱨᱥᱤᱴᱤ ᱠᱷᱚᱱ ᱰᱚᱠᱴᱚᱨ ᱚᱯᱷ ᱞᱤᱴᱟᱨᱮᱪᱟᱨ ᱩᱯᱟᱹᱫᱷᱤ ᱦᱚᱸᱠᱚ ᱮᱢ ᱟᱠᱟᱣ ᱟᱫᱮᱭᱟ᱾ ᱥᱟᱱᱛᱟᱲ ᱥᱚᱢᱟᱡᱽ ᱨᱮᱱ ᱡᱚᱛᱚ ᱠᱷᱚᱱ ᱢᱟᱨᱟᱝ ᱜᱩᱨᱩ ᱢᱮᱱᱛᱮ ᱩᱱᱤᱫᱚᱠᱚ ᱢᱟᱱᱟᱣ ᱮᱭᱟ᱾ ᱜᱩᱨᱩ ᱜᱚᱢᱠᱮ ᱯᱚᱸᱰᱮᱛ ᱨᱟᱹᱜᱷᱩᱱᱟᱛ ᱢᱩᱨᱢᱩ ᱤᱝᱨᱮᱡᱤ ᱑᱙᱘᱒ ᱥᱮᱨᱢᱟ ᱨᱮᱱᱟᱜ ᱑ ᱯᱷᱮᱵᱨᱩᱟᱨᱤ ᱨᱮᱭ ᱵᱚᱸᱜᱟ ᱛᱟᱞᱟᱭᱮᱱᱟ᱾',
        Thaana: 'ވެހިބަހަކީ ދިވެހިރާއްޖޭގެ ރަސްމީ ބަހެވެ. މި ބަހުން ވާހަކަ ދައްކައި އުޅެނީ ދިވެހިރާއްޖޭގެ އަހުލުވެރިންގެ އިތުރުން ހިންދުސްތާނުގެ މަލިކު ގެ އަހުލުވެރިންނެވެ. އެބައިމީހުން ވާހަކަ ދައްކައި އުޅެނީ ދިވެހިބަހުގެ މަހަލް ބަހުރުވައެވެ. ބަހާބެހޭ މާހިރުން ދިވެހިބަސް ހިމަނުއްވައިފައިވަނީ އިންޑޯ އާރިޔަން ބަސްތަކުގެ ތެރޭގަ އެވެ. ދިވެހި ބަހުގެ މަތިކޮޅުގައި އެންމެ ކުރީޒަމާނުގައި އޮތް މައި ބަސް " ޕުރޯޓޯ- އިންޑޯ- ޔޫރަޕިއަން" ބަހުން ވާހަކަދައްކާ އުލުނު ބަޔަކު ދެބަޔަކަށް ބެހިގެން، އެއްބަޔަކު ހުޅަނގުގެ ރަށްރަށަށް އަނެއްބަޔަކު އިރުމަތީ ރަށްރަށަށް ގޮސް އެތަންތާނގައި ރަށްވެހިވީ އެވެ. މި މީހުން ވާހަކަދައްކާ އުޅުނު ބަސް ބަދަލުވެ ތަރައްޤީވެ ވަކި ބަސް ބަހަށްވީ އެތައް ވޭލާއެއްގެ ނުވަތަ ޒަމާނެއްގެ ތެރޭގަ އެވެ. އިރުމައްޗަށް އައި މައިގަނޑު ބަހަކީ އިންޑޯ- އިރޭނިއަން ބަހެވެ. މި ބަސް ކަފިވީ އިރޭނިއަން ބަހަށާއި، އިންޑޯ އާރިއަން )ސާންސްކިރިތު (ބަހަށެވެ. މިދެންނެވި ސާންސްކިރިތުގެ ހުޅަނގާއި، ހުޅަނގު ދެކުނުގެ ބައިގައިވަނީ ގުޖަރާތީ މަރާޓީ ކޮންކަނީ، ދިވެހި، ސިންހަޅަ، މި ބަސްބަހެވެ، ވީމާ، މިބަސް ތަކުގައި ބޭނުންކުރާ ލަފުޒުތަކާއި،ޤަވާއިދާއި އަދި ބަހުގެ އަދަބުތަކުގައި ތިމާގެކަންހުރެ އެވެ. ހުޅަނގަށް ގޮސްފައިވާ ގޮފީގެ ބަސްތަކާއި، އަލުގަނޑުމެންގެ އިންޑިކު ނުވަތަ ސާންސްކިރިތުން އުފެދިފައިވާ ބަސްތަކާއި ވަރަށް ތަފާތެވެ. އިނގިރާސި ބަހަކީ މިދެންނެވި ހުޅަނގަށް ގޮސްފައިވާ ގޮފީގެ އަލްމާނީ ބަހެކެވެ.',
        Kharoshthi: '𐨐𐨆𐨠𐨂 𐨗𐨱𐨁 𐨬𐨁𐨤𐨿𐨪𐨩𐨱𐨅𐨀 𐨨𐨞<br/>𐨯𐨙𐨆𐨩𐨞 𐨯𐨬𐨁 𐨀𐨡𐨁𐨐𐨨𐨅𐨀<br/>𐨟 𐨣𐨨𐨪𐨂𐨬𐨯 𐨀𐨮𐨗𐨨𐨞<br/>𐨀𐨐𐨁𐨗𐨞 𐨣𐨞𐨂𐨬𐨡𐨡𐨁 𐨡𐨂𐨑𐨂<br/><br/>𐨗𐨁𐨞 𐨐𐨆𐨢 𐨀𐨐𐨆𐨠𐨅𐨞 <br/>𐨀𐨯𐨢𐨂 𐨯𐨢𐨂𐨞 𐨗𐨁𐨞<br/>𐨗𐨁𐨞 𐨐𐨿𐨪𐨡𐨬 𐨡𐨞𐨅𐨞 <br/>𐨯𐨕𐨅𐨞 𐨀𐨫𐨁𐨀 𐨗𐨁𐨞',
        PhagsPa: '〔ꡳꡡ〕ꡳꡎꡜꡖꡱꡟ ꡛꡧꡖ ꡜꡖ ᠅ ꡳꡡ ꡋ ꡏꡡ ꡎꡜ ꡂ ꡓ〔ꡈꡠ〕ꡛꡘ ꡓ ꡈꡱꡗꡞ ꡙꡡ ꡀꡨ ᠃ ꡎꡱ ꡈꡞ〔ꡓꡞ〕ꡚꡞꡚ ꡩꡖ ꡗ ᠃ ꡎꡟꡊ ꡊꡜꡖ ꡗ ꡈꡠ ꡋ ꡏ 〔…〕ꡗ ꡉꡖ ꡳꡡ ꡳꡎꡜꡖꡱꡟ ꡳꡎꡜꡖꡘꡟ ꡳꡎꡜꡖꡘꡟ ꡚꡡ ꡊꡜ ꡗ ꡚꡡ ꡊꡜ ꡗ ᠃ ꡓꡞ ꡚꡡ ꡊꡜ ꡗ ꡓꡞ ꡚꡡ ꡊꡜ ꡗ ᠃ ꡝ ꡛ ꡏ ᠂ ꡛ ꡏꡋ ꡈ ᠃ 〔ꡝ〕 ꡎꡜꡖ ꡛ ꡛꡎꡖ ꡘ ꡬ ꡂ ꡈꡞ ꡂ ꡂ〔ꡋ ꡛꡧ〕ꡎꡜꡖ ꡓ ꡓꡞ ꡚꡟꡊ ꡊꡜꡠ ᠂ ꡝ ꡎꡜꡞ ꡚꡞꡋ ꡐꡋ ꡈꡟ ꡳꡏꡖ ᠃ ꡛꡘ ꡓ 〔…〕ꡈ ꡛꡟ ꡂ ꡈ ᠃ ꡓ ꡘ ꡓ ꡐ ꡋ〔…〕ꡚꡠ ꡀꡖꡠꡘ ᠃ ꡏ ꡜꡖ ꡏꡟ ꡊꡱꡖ ꡏꡋ ꡈꡱ ꡌ ꡊꡖꡠ ᠃〔ꡝꡖ〕ꡜ ꡘ ꡝꡖ ꡜ ꡘ ᠂ ꡏ ꡏ ꡝ ꡗꡟꡘ ꡛꡋ ꡊ〔… ꡬꡞ ᠂ ꡚꡡ ꡊꡜ ꡗ ꡚꡡ〕ꡊꡜ ꡗ ᠃ ꡓꡞ ꡚꡡ ꡊꡜ ꡗ ꡓꡞ ꡚꡡ ꡊꡜ ꡗ ᠃ ꡂ ꡂ ꡋ ꡛꡧ ꡎꡜꡖ ꡓ ᠃ ꡓꡞ ꡚꡟꡊ ꡊꡜꡠ ꡟꡚ ꡬꡞ 〔… ꡓꡞ ꡆ ꡗ ᠃ ꡍ ꡘꡞ ꡚꡟꡊ〕ꡊꡜꡠ ꡛ ꡜ ꡛꡱ ᠃ ꡘꡚ ꡏꡞ ꡛꡋ ꡐꡡ ꡊꡞ ꡈꡠ ᠃ ꡛꡘ ꡓ ꡈ ꡉꡖ ꡂ ꡈ ᠃ ꡝ ꡓ ꡙꡡ ꡀꡞ ꡋꡞ ᠂ ꡚ ꡩꡖ ꡌ 〔… ꡈ ᠃ ꡌ ꡘꡞ〕ꡌꡖꡟ ꡘ ꡬꡞ ꡛꡘ ꡓ ꡈ ꡉꡖ ꡂ ꡈ ᠃ ꡏꡖ ꡈꡞ ꡊ ꡚ ꡎꡜꡟ ꡏꡞ ᠃ ꡌꡱ ꡈꡞꡚ ꡪꡞ ꡈꡠ ᠃ ꡛꡘ ꡓ ꡈ ꡉꡖ〔… ꡈ ᠃ ꡜꡱꡞ ꡊ ꡗ〕᠃ ꡝ ꡊꡜꡞꡚ ꡪꡖ〔ꡋ〕᠂ ꡝ ꡊꡜꡞꡚ ꡪꡞ ꡈꡠ ᠃ ꡏꡟ ꡊꡱꡠ ꡏꡟ ꡊꡱꡠ ᠃ ꡏ ꡜꡖ ꡏꡟ ꡊꡱꡠ ᠃ ꡎ ꡒꡱ ꡀꡖ ꡗ ᠃ ꡳꡛ ꡜ〔… ꡌ〕ꡘꡞ ꡚꡟꡊ ꡊꡜꡠ ᠃ ꡛꡘ ꡓ ꡀꡘ ꡏ ᠃ ꡝ ꡓ ꡘ ꡬ ᠃ ꡓꡞ ꡚꡟꡊ ꡊꡜꡠ ᠃ ꡌꡱ ꡈꡞ ꡋꡞ ꡓꡘ ꡈ ꡗ ᠃ ꡏ ꡏ ꡝ ꡗꡟꡘ ꡓꡞ ꡚꡟꡊ 〔ꡊꡜꡠ ᠃〕ꡛꡘ ꡓ ꡈ ꡉꡖ ꡂ ꡈ ꡛ ꡏ〔ꡗ〕᠃ ꡝ ꡊꡜꡞꡚ ꡪꡖ︀ ꡋ ᠃ ꡝ ꡊꡜꡞꡚ ꡪꡞ ꡈꡠ ᠂ ꡳꡡ ꡏꡟ ꡋꡞ ꡏꡟ ꡋꡞ ᠂ ꡏ ꡜꡖ ꡏꡟ ꡋꡞ ᠂ ꡓꡞ ꡏꡟ 〔ꡋꡞ ᠂〕ꡓꡞ ꡏꡟ ꡋꡞ ᠂ ꡏ ꡜꡖ ꡓꡞ ꡏꡟ ꡋꡞ ᠂ ꡏ ꡈꡞ ꡏ ꡈꡞ ᠃ ꡏ ꡜꡖ ꡏ ꡈꡞ ᠃ ꡏ ꡏ ꡈꡞ ꡛꡟ ꡏ ꡈꡞ ᠃ ꡈ ꡉ ꡈꡖ ᠃ ꡎꡜꡟ ꡈ ꡀ〔…〕ꡘꡞ ꡚꡟꡊ ꡊꡜꡠ ᠃ ꡓꡞ ꡛꡍꡟ ꡩ ᠃ ꡎꡟꡊ ꡊꡜꡠ ꡚꡟꡊ ꡊꡜꡠ ᠃ ꡜꡠ ꡜꡠ ꡒ ꡗ ꡒ ꡗ ᠃ ꡓꡞ ꡒ ꡗ ꡓꡞ ꡒ ꡗ ᠃ ꡛꡏꡖ ꡘ ꡛꡏꡖ ꡘ ꡛ〔ꡍꡖ ꡘ〕ꡛꡍꡖ ꡘ ᠃ ꡛꡍꡖ ꡘ ꡗ ꡛꡍꡖ ꡘ ꡗ ᠃ ꡛꡘ ꡓ ꡎꡟꡊ ꡊꡜ ꡝ ꡊꡜꡚ ꡪꡖ ꡋ 〔ꡝ〕ꡊꡜꡞꡚ ꡪꡞ ꡈꡠ ᠃ ꡚꡟꡊ ꡊꡜꡠ ꡚꡟꡊ ꡊ〔ꡜꡠ ᠃〕ꡎꡟꡊ ꡊꡜꡠ ꡎꡟꡊ ꡊꡜꡠ ᠃ ꡎ ꡒꡱꡠ ꡎ ꡒꡱꡠ ᠃ ꡏ ꡜꡖ ꡎ ꡒꡱꡠ ᠃ ꡛꡟ ꡎ ꡒꡱꡠ ᠃ ꡎ ꡒꡱꡠ ꡂꡘ ꡎꡜꡠ ᠂ ꡒ ꡗ ꡂꡘ ꡎꡜꡠ ᠃ ꡓꡞ ꡒ ꡗ ꡂꡘ ꡎꡜꡠ ꡎ ꡒꡱ ꡒꡧ ꡙ ꡂꡘ ꡎꡜꡠ ᠃ ꡎ ꡒꡱ ꡟꡊ ꡎꡜ ꡓꡠ ᠃ ꡎ ꡒꡱ ꡛꡏ ꡎꡜ ꡓꡠ ᠃ ꡎ ꡒꡱꡠ ꡎ ꡒꡱꡞ ꡋꡞ ᠃ ꡎ ꡒꡱꡏ ꡎꡜ ꡓ ꡈꡟ ᠃ ꡏ ꡏ ꡚ ꡘꡞ ꡳꡘ ᠃ ꡛꡘ ꡓ ᠃ ꡛ ꡈꡧꡖ ꡋꡖꡋ ꡐ ᠃ ꡀꡖ ꡗ ꡌ ꡘꡞ ꡚꡟꡊ ꡊꡜꡞꡘ ᠃ ꡎꡜ ꡓ ꡈꡟ ᠃ 〔…〕ꡊꡖ ꡏꡠ᠂ ꡛꡘ ꡓ ꡂ ꡈꡞ ᠃ ꡌ ꡘꡞ ꡚꡟꡘ ꡊꡜꡞꡚ ꡐ ᠃ ꡛꡘ ꡓ ꡈ ꡉꡖ ꡂ ꡈꡚ ꡐ ꡳꡏꡖꡏ ᠃ ꡛꡋ ꡝꡚ ꡓꡖ ꡛ ꡗꡋ ꡈꡟ ᠃ ꡎꡟꡊ ꡊꡜꡨ ꡎꡟꡊ ꡊꡜꡨ ᠂ ꡛꡞꡊ ꡊꡜꡨ ꡛꡞꡊ ꡊꡜꡨ ᠃ ꡎꡡ ꡊꡜ ꡗ ꡎꡡ ꡊꡜ ꡗ ᠃ ꡓꡞ ꡎꡡ ꡊꡜ ꡗ ꡓꡞ ꡎꡡ ꡊꡜ ꡗ ᠃ ꡏꡡ ꡐ ꡗ ꡏꡡ ꡐ ꡗ ᠃ ꡓꡞ ꡏꡡ ꡐ ꡗ ꡓꡞ ꡏꡡ ꡐ ꡗ ᠃ ꡚꡡ ꡊꡜ 〔ꡗ〕ꡚꡡ ꡊꡜ ꡗ ᠃ ꡓꡞ ꡚꡡ ꡊꡜ ꡗ ꡓꡞ ꡚꡡ ꡊꡜ ꡗ ᠃ ꡛ ꡏꡋ ꡈꡖ ꡏꡡ ꡐ ꡗ ꡏꡡ ꡐ ꡗ ᠃ ꡛ ꡏꡋ ꡈ ꡘꡚ ꡏꡞ ꡎ ꡘꡞ ꡚꡟꡊ ꡊꡜꡞ ᠃ ꡛꡘ ꡓ ꡈ ꡉꡖ ꡂ  〔ꡈ〕ꡜꡱꡞ ꡊ ꡗ ᠃ ꡝ ꡊꡜꡞꡚ ꡪꡖ ꡋ ꡝ ꡊꡜꡞꡚ ꡪꡖ〔ꡋ 〕᠃ ꡏꡟ ꡊꡱꡠ ꡏꡟ ꡊꡱꡠ ᠂ ꡏ ꡜꡖ ꡏꡟ ꡊꡱꡠ ᠃ ꡏ ꡜꡖ ꡏꡟ ꡊꡱꡖ ꡏꡋ ꡈꡱ ꡌ ꡊꡖꡠ ꡛꡧꡖ ꡜꡖ',
        'Sundanese': 'ᮞᮊᮥᮙ᮪ᮔ ᮏᮜ᮪ᮙ ᮌᮥᮘᮢᮌ᮪ ᮊ ᮃᮜᮙ᮪ ᮓᮥᮑ ᮒᮨᮂᮞᮤᮖᮒ᮪ᮔ ᮙᮨᮛ᮪ᮓᮤᮊ ᮏᮩᮀ ᮘᮧᮌ ᮙᮛ᮪ᮒᮘᮒ᮪ ᮊᮒᮥᮒ᮪ ᮠᮊ᮪-ᮠᮊ᮪ ᮃᮔᮥ ᮞᮛᮥᮃ. ᮙᮛᮔᮨᮂᮔ ᮓᮤᮘᮨᮛᮨ ᮃᮊᮜ᮪ ᮏᮩᮀ ᮠᮒᮨ ᮔᮥᮛᮔᮤ, ᮎᮙ᮪ᮕᮥᮁ-ᮌᮅᮜ᮪ ᮏᮩᮀ ᮞᮞᮙᮔ ᮃᮚ ᮓᮤᮔ ᮞᮥᮙᮔᮨᮒ᮪ ᮓᮥᮓᮥᮜᮥᮛᮔ᮪.',
        'Limbu': 'ᤀᤠᤱᤃᤠ᤹ ᤐᤣᤴᤛ᤺ᤴ ᤁᤧᤗ᤺ᤶᤒᤠ᤹ ᤔᤏᤠᤀᤠ॥ ᤀᤠᤜᤡᤶ ᤑᤢᤱᤗᤧᤱ, ᤀᤠᤱᤃᤠ᤹ ᤀᤠᤳᤋᤡᤴᤏᤠᤱ ᤛᤠᤶᤕᤠᤣᤏᤡᤒᤠ, ᤛᤠᤶᤕᤠᤣᤌᤡᤶᤜᤠ᤹ ᤏᤛᤠ᤺ᤴ ᤔᤧᤴᤈᤠᤣᤰᤏᤠᤒᤠ ᤀᤠ॥ ᤌᤡᤰᤕᤣᤶ ᤁᤡᤵᤔᤠ ᤁᤣᤄᤢᤒᤠ ᤋᤢᤰᤔᤠᤸᤗᤣ ᤕᤠᤱᤛᤠᤱ, ᤛᤡᤍᤠᤒᤠᤱᤍᤠ᤹ ᤔᤧᤳᤇᤡᤱᤛᤧ ᤐᤣᤃᤠᤱᤛᤠᤱ ᤔᤧᤴᤏᤢ᤺ᤒᤠ ᤁᤖ ᤕᤧᤛᤢᤔᤠᤱᤀᤠᤣ ᤏᤛᤠᤴ ᤆᤠ᤺ᤣᤰ ᤜᤣᤶᤋᤢᤅᤠᤱᤎᤠᤣ ᤀᤠᤱᤃᤠ ᤘᤣᤳᤋᤠᤱ ᤒᤠᤖᤠᤣ॥ - ᤗᤠᤗ ᤒᤜᤠᤍᤢᤖ ᤗᤡᤶᤒᤢ. ᤁᤱ ᤏᤢᤛᤡᤕᤣᤰᤐᤠ ᤕᤠᤰᤐᤱᤃᤧᤶᤒᤠ ᤛᤣᤛᤣ ᤆᤢᤶᤗᤢᤱ ᤁᤠᤗᤣᤶᤐᤠᤣᤱ ᤒᤠ ᤆᤀᤡᤳᤖᤠᤣ॥ ᤀᤠᤸᤗᤒᤠ ᤕᤧᤳᤇᤡ᤹ᤃᤣᤶᤐᤠ ᤛᤣᤛᤣ ᤆᤢᤶᤗᤢᤱ ᥇᥇ ᤀᤰᤋᤢᤒᤖ ᥈᥆᥇᥊ ᤛᤡᤗᤡᤃᤢᤍᤡ ᥋᥆᥆ ᤔᤏᤠᤗᤶᤔᤠᤣ ᤐᤠ᤺ᤣᤱᤗ ᤐᤳᤗᤠᤣ॥',
        'Urdu': 'گوتم بدھ کو بدھا اور بدھ کے نام سے بھی پکارا جاتا ہے۔ ان کا اصل نام سدھارتھ تھا۔ یہ563قبل مسیح یا 480 قبل مسیح میں پیدا ہوئے۔ ان کا باپ ایک ریاست، جو علاقہ اب موجودہ نیپال میں شامل ہے، کا راجا تھا اس ریاست کو کپل وستو کہا جاتا تھا۔ گوتم بدھ بدھ مت مذہب کے بانی ہیں۔ اب سے تقریباً 25 سو برس پیشتر قدیم برہمنوں کے عہد کے اختتام پر کوشل کی طاقتور سلطنت کے کچھ مشرق میں ساکیہ کشتری آباد تھے۔ یہ ایک چھوٹی سی قوم تھی۔ سدھوون ان کا راجا تھا۔ کپل وستو اس کی راجدھانی تھی۔ یہ شہر بنارس سے سو میل کے قریب شمال میں واقع تھا۔ سدھوون بڑا بہادر جنگجو راجا تھا اور چاہتا تھا کہ میرے بعد میرا بیٹا گوتم بھی ایسا ہی بہادر اور جنگجو ہو۔ اس نے اسے سپہ گری کے سب فن سکھائے مثلاً نیزہ بازی، تیر اندازی اور شمشیر زنی۔ گوتم جب 18 برس کا ہوا تو ایک خوبصورت شہزادی مسماۃ یشورا سے اس کی شادی ہوئی اور شادی کے دس سال بعد ان کے ہاں ایک لڑکا پیدا ہوا۔ گوتم جب پيدا ہوا تو نجوميوں نے اس كے باپ كو بتايا تھا كہ یہ بچہ بڑا ہو كر يا تو بادشاہ بنے گا يا پھر سادھو مگر جو بھی بنے گا اس جيسا دنيا ميں كوئی اور نہ ہو گا۔ اگر بادشاہ ہوا تو بہت بڑا بادشاہ ہوگا اور اگر سادھو بنا تو رہتی دنيا تک اس كا نام رہے گا۔',
        'Avestan': '𐬀𐬴𐬆𐬨 𐬬𐬊𐬵𐬏 𐬬𐬀𐬵𐬌𐬱𐬙𐬆𐬨 𐬀𐬯𐬙𐬍<br/>𐬎𐬱𐬙𐬁 𐬀𐬯𐬙𐬍 𐬎𐬱𐬙𐬁 𐬀𐬵𐬨𐬁𐬌<br/>𐬵𐬌𐬌𐬀𐬝 𐬀𐬴𐬁𐬌 𐬬𐬀𐬵𐬌𐬱𐬙𐬁𐬌 𐬀𐬴𐬆𐬨',
        'OldPersian': '𐏐 𐎠𐎭𐎶 𐏐 𐎭𐎠𐎼𐎹𐎺𐎢𐏁 𐏐 𐎧𐏁𐎠𐎹𐎰𐎡𐎹 𐏐 𐎺𐏀𐎼𐎣 𐏐 𐎧𐏁𐎠𐎹𐎰𐎡𐎹 𐏐 𐎧𐏁𐎠𐎹𐎰𐎡𐎹𐎠𐎴𐎠𐎶 <br/>𐏐 𐎧𐏁𐎠𐎹𐎰𐎡𐎹 𐏐 𐎱𐎠𐎼𐎿𐎡𐎹 𐏐 𐎧𐏁𐎠𐎹𐎰𐎡𐎹 𐏐 𐎭𐏃𐎹𐎢𐎴𐎠𐎶 𐏐 𐎻𐏁𐎫𐎠𐎿𐎱𐏃𐎹𐎠 <br/>𐏐 𐎱𐎢𐏂 𐏐 𐎠𐎼𐏁𐎠𐎶𐏃𐎹𐎠 𐏐 𐎴𐎱𐎠 𐏐 𐏃𐎧𐎠𐎶𐎴𐎡𐏁𐎡𐎹 !! 𐏐 𐎰𐎠𐎫𐎡𐎹 𐏐 <br/> 𐎭𐎠𐎼𐎹𐎺𐎢𐏁 𐏐 𐎧𐏁𐎠𐎹𐎰𐎡𐎹 𐏐 𐎶𐎴𐎠 𐏐 𐎱𐎡𐎫𐎠 𐏐 𐎻𐏁𐎫𐎠𐎿𐎱 𐏐 𐎻𐏁𐎫𐎠𐎿𐎱𐏃𐎹𐎠 𐏐 𐎱𐎡𐎫𐎠 𐏐 𐎠𐎼𐏁𐎠𐎶 <br/>𐏐 𐎠𐎼𐏁𐎠𐎶𐏃𐎹𐎠 𐏐 𐎱𐎡𐎫𐎠 𐏐 𐎠𐎼𐎡𐎹𐎠𐎼𐎶𐎴 𐏐 𐎠𐎼𐎡𐎹𐎠𐎼𐎶𐎴𐏃𐎹𐎠 𐏐 𐎱𐎡𐎫𐎠 𐏐 𐎨𐎡𐏁𐎱𐎡𐏁 𐏐 𐎨𐎡𐏁𐎱𐎠𐎡𐏁 <br/>𐏐 𐎱𐎡𐎫𐎠 𐏐 𐏃𐎧𐎠𐎶𐎴𐎡𐏁 !! 𐏐 𐎰𐎠𐎫𐎡𐎹 𐏐 𐎭𐎠𐎼𐎹𐎺𐎢𐏁 𐏐 𐎧𐏁𐎠𐎹𐎰𐎡𐎹 𐏐 𐎠𐎺𐏃𐎹𐎼𐎠𐎮𐎡𐎹 <br/>𐏐 𐎺𐎹𐎶 𐏐 𐏃𐎧𐎠𐎶𐎴𐎡𐏁𐎡𐎹𐎠 𐏐 𐎰𐏃𐎹𐎠𐎶𐏃𐎹 𐏐 𐏃𐎨𐎠 𐏐 𐎱𐎽𐎢𐎻𐎡𐎹𐎫 𐏐 𐎠𐎶𐎠𐎫𐎠 𐏐 𐎠𐎶𐏃𐎹 <br/>𐏐 𐏃𐎨𐎠 𐏐 𐎱𐎽𐎢𐎻𐎡𐎹𐎫 𐏐 𐏃𐎹𐎠 𐏐 𐎠𐎶𐎠𐎧𐎶 𐏐 𐎫𐎢𐎶𐎠 𐏐 𐎧𐏁𐎠𐎹𐎰𐎡𐎹𐎠 𐏐 𐎠𐏃 !! 𐏐 𐎰𐎠𐎫𐎡𐎹 <br/>𐏐 𐎭𐎠𐎼𐎹𐎺𐎢𐏁 𐏐 𐎧𐏁𐎠𐎹𐎰𐎡𐎹 𐏐 𐏒𐏒𐏒𐏒 𐏐 𐎶𐎴𐎠 𐏐 𐎫𐎢𐎶𐎠𐎹𐎠 𐏐 𐎫𐎹𐎡𐎹 𐏐 𐎱𐎽𐎢𐎺𐎶 <br/>𐏐 𐎧𐏁𐎠𐎹𐎰𐎡𐎹𐎠 𐏐 𐎠𐏃 𐏐 𐎠𐎭𐎶 𐏐 𐎴𐎺𐎶 𐏐 𐏒𐏒𐏒𐏒𐏑 𐏐 𐎯𐎢𐎻𐎡𐎫𐎠𐎱𐎼𐎴𐎶 𐏐 𐎺𐎹𐎶 𐏐 𐎧𐏁𐎠𐎹𐎰𐎡𐎹𐎠 <br/>𐏐 𐎠𐎶𐏃𐎹 !! 𐏐 𐎰𐎠𐎫𐎡𐎹 𐏐 𐎭𐎠𐎼𐎹𐎺𐎢𐏁 𐏐 𐎧𐏁𐎠𐎹𐎰𐎡𐎹 𐏐 𐎺𐏁𐎴𐎠 𐏐 𐎠𐎢𐎼𐎶𐏀𐎭𐎠𐏃 <br/>𐏐 𐎠𐎭𐎶 𐏐 𐎧𐏁𐎠𐎹𐎰𐎡𐎹 𐏐 𐎠𐎷𐎡𐎹 𐏐 𐎠𐎢𐎼𐎶𐏀𐎭𐎠 𐏐 𐎧𐏁𐏂𐎶 𐏐 𐎶𐎴𐎠 𐏐 𐎳𐎼𐎠𐎲𐎼 !! 𐏐 𐎰𐎠𐎫𐎡𐎹 <br/>𐏐 𐎭𐎠𐎼𐎹𐎺𐎢𐏁 𐏐 𐎧𐏁𐎠𐎹𐎰𐎡𐎹 𐏐 𐎡𐎶𐎠 𐏐 𐎭𐏃𐎹𐎠𐎺 𐏐 𐎫𐎹𐎠 𐏐 𐎶𐎴𐎠 𐏐 𐎱𐎫𐎡𐎹𐎠𐎡𐏁 𐏐 𐎺𐏁𐎴𐎠 <br/>𐏐 𐎠𐎢𐎼𐎶𐏀𐎭𐎠𐏃 𐏐 𐎠𐎭𐎶𐏁𐎠𐎶 𐏐 𐎧𐏁𐎠𐎹𐎰𐎡𐎹 𐏐 𐎠𐏃𐎶 𐏐 𐎱𐎠𐎼𐎿 𐏐 𐎢𐎺𐎩 𐏐 𐎲𐎠𐎲𐎡𐎽𐎢𐏁 𐏐 𐎠𐎰𐎢𐎼𐎠 <br/>𐏐 𐎠𐎼𐎲𐎠𐎹 𐏐 𐎸𐎢𐎭𐎼𐎠𐎹 𐏐 𐎫𐎹𐎡𐎹 𐏐 𐎭𐎼𐎹𐏃𐎹𐎠 𐏐 𐎿𐎱𐎼𐎭 𐏐 𐎹𐎢𐎴 𐏐 𐎶𐎠𐎭 𐏐 𐎠𐎼𐎷𐎡𐎴 𐏐 𐎣𐎫𐎱𐎬𐎢𐎣 <br/>𐏐 𐎱𐎼𐎰𐎺 𐏐 𐏀𐎼𐎣 𐏐 𐏃𐎼𐎡𐎺 𐏐 𐎢𐎺𐎠𐎼𐏀𐎷𐎡𐎹 𐏐 𐎲𐎠𐎧𐎫𐎼𐎡𐏁 𐏐 𐎿𐎢𐎦𐎢𐎭 𐏐 𐎥𐎭𐎠𐎼 𐏐 𐎿𐎣 <br/>𐏐 𐎰𐎫𐎦𐎢𐏁 𐏐 𐏃𐎼𐎢𐎺𐎫𐎡𐏁 𐏐 𐎶𐎣 𐏐 𐎳𐎼𐏃𐎼𐎺𐎶 𐏐 𐎭𐏃𐎹𐎠𐎺 𐏐 𐏔𐏒𐏑 !! 𐏐 𐎰𐎠𐎫𐎡𐎹 𐏐 𐎭𐎠𐎼𐎹𐎺𐎢𐏁 <br/>𐏐 𐎧𐏁𐎠𐎹𐎰𐎡𐎹 𐏐 𐎡𐎶𐎠 𐏐 𐎭𐏃𐎹𐎠𐎺 𐏐 𐎫𐎹𐎠 𐏐 𐎶𐎴𐎠 𐏐 𐎱𐎫𐎡𐎹𐎠𐎡𐏁 𐏐 𐎺𐏁𐎴𐎠 𐏐 𐎠𐎢𐎼𐎶𐏀𐎭𐎠𐏃'
      }
    }
  },
  watch: {
    '$route' (to, from) {
      this.script1 = to.params.script
    },
    script1: async function () {
      this.compoundsGen()
    },
    script2: async function () {
      this.compoundsGen()
    }
  },
  mounted: function () {
    this.compoundsGen()
  },
  methods: {
    compoundsGen: async function () {
      this.loading = true
      var data = {
        text: this.charList,
        script1: this.script1,
        script2: this.script2
      }
      var dhis = this
      this.apiCall.post('/describe', data)
        .then(function (response) {
          dhis.charListC['script1'] = JSON.parse(response.data['script1'].replace(/،/g, ','))
          dhis.charListC['script2'] = JSON.parse(response.data['script2'].replace(/،/g, ','))
          dhis.charListC['script1hk'] = JSON.parse(response.data['script1hk'].replace(/،/g, ','))
          dhis.$set(dhis, 'charListC', dhis.charListC)
          dhis.loading = false
          console.log(response.data)
        })
        .catch(function (error) {
          console.log(error)
        })
    }
  }
}
</script>
